// 📆 22/06 📅
// 🏟️ Arena Meudon 📍

// 🆘🆘 ATENÇÃO AO HORÁRIO DE INÍCIO 🆘🆘 👉🏻 08:55

// 🙋🏻‍♂️ MENSALISTAS 💚

// 1 - Thomaz ✅
// 2 - Gabriel ✅
// 3 - Chico 🔁 Leandrinho
// 4 - Ravel 🔁 Danrley
// 5 - Cristiano 🔃Renan
// 6 - Andin ✅
// 7 - Erly ✅
// 8 - Reinaldo✅
// 9 - Thiago✅
// 10- Nathan✅
// 11- LG ✅
// 12- Felipe ✅
// 13- Gustavo 🔁 Igor
// 14- André 🔁 Dogão
// 15- Yago ✅

// 🚦 LEGENDA DOS MENSALISTAS:
// ❓- Ainda não confirmou
// ✅ - Confirmado
// ❌ - Fora da Pelada (Dará lugar à Lista de Espera)

// 🧤 GOLEIROS 🥅
// 1 -  Da Cruz
// 2 - Gean
// 3 - Gustavo Ramos

// ⏳ LISTA DE ESPERA ⏳
// ⏱️ 1- Da Cruz
// ⏱️ 2- Breno

// 💰PIX (Thomaz | Banco C6) CPF: 129.640.657-13💰
